game:
    task: "emergence"
tracking:
    max_players: 10
detection:
    min_contour: 100
    max_contour: 500
    min_hsv: [ 50, 170, 100]
    max_hsv: [ 85, 255, 255]
camera:
    iso: 100
    saturation: 100
    shutter_speed: 31250
    awb_mode: "sunlight"

